baseURL = "https://hojjang98.github.io/"
title = "HJ's Security Note"
theme = "PaperMod"
defaultContentLanguage = "ko"
languageCode = "ko-kr"
enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      hardLineBreak = true

[params]
  showShareButtons = false
  showReadingTime = false
  showBreadCrumbs = true

[params.profileMode]
  enabled = true
  title = "Hojun Choi"
  subtitle = "Security Governance & Legal Analysis"
  imageUrl = "profile.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Profile"

[[params.profileMode.buttons]]
  name = "소개"
  url = "/about"

[[params.profileMode.buttons]]
  name = "보안법 공부"
  url = "/categories/cyber-law-study"

[[params.profileMode.buttons]]
  name = "보안 시사 분석"
  url = "/categories/security-issues-analysis"

[[params.profileMode.buttons]]
  name = "프로젝트"
  url = "/categories/projects"

[[params.profileMode.buttons]]
  name = "논문 리뷰"
  url = "/categories/paper-review"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[minify]
  disableHTML = true  # HTML minify 비활성화